#!/usr/bin/env python3
"""Multilingual manifold visualizations for the CJK/Hindi cycles session.

Produces six figures saved to FIGURES_DIR. Run with:
    uv run python agent_logs/2026-06-10--cjk-hindi-cycles--keen-panda/code/plot_manifolds.py

Data file: manifold_data.json (generated by extract_manifold_data.py)
"""

from __future__ import annotations
import json
import os
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyArrowPatch
from scipy.interpolate import splprep, splev

# ── Paths ──────────────────────────────────────────────────────────────────────
REPO_ROOT = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..")
SESSION_DIR = os.path.join(os.path.dirname(__file__), "..")
DATA_PATH = os.path.join(SESSION_DIR, "code", "manifold_data.json")
FIGURES_DIR = os.path.join(SESSION_DIR, "result", "figures")
os.makedirs(FIGURES_DIR, exist_ok=True)

# ── Load data ──────────────────────────────────────────────────────────────────
with open(DATA_PATH) as f:
    DATA = json.load(f)

LANGS = ["en", "fr", "zh", "ja"]
LANG_LABELS = {"en": "English", "fr": "French", "zh": "Chinese", "ja": "Japanese"}
LANG_COLORS = {"en": "#1565C0", "fr": "#C62828", "zh": "#E65100", "ja": "#2E7D32"}
LANG_RING = {"en": True, "fr": False, "zh": False, "ja": False}

# Day colors: cyclic HSV wheel so that Sun→Mon feels connected
DAY_COLORS = [plt.cm.hsv(i / 7.0) for i in range(7)]
DAY_COLORS_HEX = [matplotlib.colors.to_hex(c) for c in DAY_COLORS]

ISOMETRY_R = {"en": 0.989, "fr": 0.087, "zh": 0.317, "ja": -0.101}
COHERENCE   = {"en": 0.783, "fr": 0.745, "zh": 0.966, "ja": 0.979}
PULLBACK    = {  # (opt, lin) — only EN and FR measured
    "en": (0.687, 0.419),
    "fr": (0.266, 0.530),
}
GATE_ACC = {"en": 93.9, "fr": 79.6, "zh": 67.3, "ja": 63.3}

SAFETY_OVERLAP = {
    "en→en": 1.000,
    "en→ja": 0.421,
    "en→zh": 0.242,
    "en→fr": 0.023,
}

# ── Style ──────────────────────────────────────────────────────────────────────
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 10,
    "axes.titlesize": 12,
    "axes.labelsize": 10,
    "figure.dpi": 150,
    "axes.spines.top": False,
    "axes.spines.right": False,
})


def smooth_curve(pts_2d: np.ndarray, closed: bool, n_pts: int = 300) -> np.ndarray:
    """Fit and sample a smooth spline through 2D points."""
    if closed:
        p = np.vstack([pts_2d, pts_2d[0]])
        tck, _ = splprep([p[:, 0], p[:, 1]], s=0, per=True)
    else:
        k = min(3, len(pts_2d) - 1)
        tck, _ = splprep([pts_2d[:, 0], pts_2d[:, 1]], s=0, per=False, k=k)
    u = np.linspace(0, 1, n_pts)
    x, y = splev(u, tck)
    return np.column_stack([x, y])


def angle_order(pts: np.ndarray, center: np.ndarray | None = None) -> np.ndarray:
    """Return indices that sort pts by angle around center."""
    c = center if center is not None else pts.mean(axis=0)
    angles = np.arctan2(pts[:, 1] - c[1], pts[:, 0] - c[0])
    return np.argsort(angles)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 1 — Per-language manifold panels (paper-style)
# ══════════════════════════════════════════════════════════════════════════════
def fig1_language_manifolds():
    fig, axes = plt.subplots(2, 2, figsize=(10, 10))
    fig.suptitle(
        "Weekday Cyclic Arithmetic Manifolds — Llama 3.1 8B, Layer 28\n"
        "(centroid positions in each language's best-fit 2-D subspace of pca_k64)",
        fontsize=12, y=0.98
    )

    for ax, lang in zip(axes.flat, LANGS):
        lang_data = DATA["per_language"][lang]
        entity_names = DATA["entity_names"][lang]
        is_ring = LANG_RING[lang]

        pts = np.array(lang_data["centroids_2d"])  # (7, 2)
        center = np.array(lang_data["circle_center"])
        radius = lang_data["circle_radius"]
        color = LANG_COLORS[lang]

        # Order for smooth curve
        if is_ring:
            order = angle_order(pts, center)
        else:
            order = np.arange(7)  # natural weekday order Mon→Sun
        ordered_pts = pts[order]

        # Smooth curve
        curve = smooth_curve(ordered_pts, closed=is_ring)

        # Draw curve
        ls = "-" if is_ring else "--"
        ax.plot(curve[:, 0], curve[:, 1], color=color, lw=2, ls=ls, alpha=0.6,
                zorder=1, label="Fitted ring" if is_ring else "Fitted spline")

        if is_ring:
            # Draw best-fit circle for reference
            theta = np.linspace(0, 2 * np.pi, 300)
            cx, cy = center
            ax.plot(cx + radius * np.cos(theta), cy + radius * np.sin(theta),
                    color=color, lw=0.8, ls=":", alpha=0.3, zorder=0)

        # Scatter centroids colored by weekday
        for i, name in enumerate(entity_names):
            dc = DAY_COLORS[i]
            ax.scatter(pts[i, 0], pts[i, 1], color=dc, s=120, zorder=3,
                       edgecolors="white", linewidths=0.8)
            # Label offset to avoid overlap
            dx, dy = pts[i, 0] - pts.mean(0)[0], pts[i, 1] - pts.mean(0)[1]
            norm = np.sqrt(dx**2 + dy**2) + 1e-8
            ax.annotate(name, (pts[i, 0], pts[i, 1]),
                        xytext=(pts[i, 0] + 0.25 * dx / norm * radius,
                                pts[i, 1] + 0.25 * dy / norm * radius),
                        fontsize=7.5, ha="center", va="center",
                        bbox=dict(boxstyle="round,pad=0.1", fc="white", alpha=0.6, ec="none"))

        ring_str = "Closed ring ✓" if is_ring else "Open spline"
        ax.set_title(
            f"{LANG_LABELS[lang]}  ({lang.upper()})  |  Gate {GATE_ACC[lang]:.0f}%\n"
            f"{ring_str}  |  Isometry r = {ISOMETRY_R[lang]:+.3f}  |  Coherence = {COHERENCE[lang]:.3f}",
            fontsize=9.5, color=color
        )
        ax.set_xlabel("PC 1 (language subspace)", fontsize=8)
        ax.set_ylabel("PC 2 (language subspace)", fontsize=8)
        ax.set_aspect("equal")
        ax.tick_params(labelsize=7)

    fig.tight_layout(rect=[0, 0, 1, 0.97])
    path = os.path.join(FIGURES_DIR, "fig1_language_manifolds.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 2 — Joint embedding (all 4 languages in shared 2-D PCA)
# ══════════════════════════════════════════════════════════════════════════════
def fig2_joint_embedding():
    fig, ax = plt.subplots(figsize=(8, 7))
    joint = DATA["joint_embedding"]
    ev1, ev2 = DATA["joint_ev1"], DATA["joint_ev2"]

    legend_handles = []
    for lang in LANGS:
        pts = np.array(joint[lang])   # (7, 2) in joint PCA space
        is_ring = LANG_RING[lang]
        color = LANG_COLORS[lang]
        entity_names = DATA["entity_names"][lang]
        center_j = pts.mean(axis=0)

        if is_ring:
            order = angle_order(pts, center_j)
        else:
            order = np.arange(7)
        ordered_pts = pts[order]

        curve = smooth_curve(ordered_pts, closed=is_ring)
        ls = "-" if is_ring else "--"
        ax.plot(curve[:, 0], curve[:, 1], color=color, lw=2, ls=ls, alpha=0.7, zorder=2)

        for i, name in enumerate(entity_names):
            ax.scatter(pts[i, 0], pts[i, 1], color=color, s=80,
                       edgecolors="white", linewidths=0.6, zorder=3)

        # Language label near centroid
        mean_pos = pts.mean(axis=0)
        ax.text(mean_pos[0], mean_pos[1] - 0.5, LANG_LABELS[lang],
                color=color, fontsize=9, ha="center", fontweight="bold")

        lbl = f"{LANG_LABELS[lang]} ({'ring' if is_ring else 'spline'})"
        legend_handles.append(mpatches.Patch(color=color, label=lbl))

    ax.set_xlabel(f"Joint PC 1 ({100*ev1:.1f}% var.)", fontsize=10)
    ax.set_ylabel(f"Joint PC 2 ({100*ev2:.1f}% var.)", fontsize=10)
    ax.set_title(
        "All Language Weekday Centroids — Shared 2-D PCA\n"
        "(Llama 3.1 8B, Layer 28, pca_k64 features)",
        fontsize=12
    )
    ax.set_aspect("equal")
    ax.legend(handles=legend_handles, loc="upper right", fontsize=8)
    ax.tick_params(labelsize=8)

    fig.tight_layout()
    path = os.path.join(FIGURES_DIR, "fig2_joint_embedding.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 3 — Cross-lingual subspace alignment: pairwise joint projections
# ══════════════════════════════════════════════════════════════════════════════
def fig3_subspace_alignment():
    main_pairs = [("en", "zh"), ("en", "fr"), ("zh", "ja")]
    pair_titles = {
        "en_vs_zh": "English ↔ Chinese",
        "en_vs_fr": "English ↔ French",
        "zh_vs_ja": "Chinese ↔ Japanese",
    }

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle(
        "Cross-lingual Subspace Alignment: Pairwise Joint 2-D Projections\n"
        "(Both languages' centroids projected into their shared PCA plane)",
        fontsize=12
    )

    for ax, (la, lb) in zip(axes, main_pairs):
        key = f"{la}_vs_{lb}"
        pair_data = DATA["pairwise_joint_embedding"][key]
        align = DATA["pairwise_alignment"][key]

        for lang in [la, lb]:
            proj = pair_data["projections"][lang]
            pts = np.array(proj["coords"])
            r = proj["radius"]
            entity_names = DATA["entity_names"][lang]
            color = LANG_COLORS[lang]
            is_ring = LANG_RING[lang]
            center = pts.mean(axis=0)

            if is_ring:
                order = angle_order(pts, center)
            else:
                order = np.arange(7)
            ordered_pts = pts[order]
            curve = smooth_curve(ordered_pts, closed=is_ring)

            ls = "-" if is_ring else "--"
            ax.plot(curve[:, 0], curve[:, 1], color=color, lw=2.5, ls=ls, alpha=0.7)
            for i, name in enumerate(entity_names):
                ax.scatter(pts[i, 0], pts[i, 1], color=color, s=90,
                           edgecolors="white", linewidths=0.7, zorder=3)
            # Language label
            ax.text(center[0], center[1], LANG_LABELS[lang],
                    color=color, fontsize=8, ha="center", va="center",
                    fontweight="bold",
                    bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.7, ec="none"))

        theta1 = align["theta1"]
        theta2 = align["theta2"]
        overlap = align["overlap"]
        r_a = pair_data["projections"][la]["radius"]
        r_b = pair_data["projections"][lb]["radius"]
        ratio = max(r_a, r_b) / (min(r_a, r_b) + 1e-10)

        ax.set_title(
            f"{pair_titles[key]}\n"
            f"θ₁={theta1:.1f}°, θ₂={theta2:.1f}°  |  Overlap={overlap:.3f}  |  Radius ratio={ratio:.1f}×",
            fontsize=9
        )
        ax.set_aspect("equal")
        ax.set_xlabel("Pair PC 1", fontsize=8)
        ax.set_ylabel("Pair PC 2", fontsize=8)
        ax.tick_params(labelsize=7)

    fig.tight_layout(rect=[0, 0, 1, 0.92])
    path = os.path.join(FIGURES_DIR, "fig3_subspace_alignment.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 4 — Subspace overlap heatmap (all 6 pairs)
# ══════════════════════════════════════════════════════════════════════════════
def fig4_overlap_heatmap():
    langs_ord = ["en", "fr", "zh", "ja"]
    n = len(langs_ord)
    matrix = np.full((n, n), np.nan)
    np.fill_diagonal(matrix, 1.0)

    for key, vals in DATA["pairwise_alignment"].items():
        la, lb = key.split("_vs_")
        if la in langs_ord and lb in langs_ord:
            i, j = langs_ord.index(la), langs_ord.index(lb)
            matrix[i, j] = vals["overlap"]
            matrix[j, i] = vals["overlap"]

    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(matrix, cmap="YlOrRd_r", vmin=0, vmax=1, aspect="auto")

    labels = [LANG_LABELS[l] for l in langs_ord]
    ax.set_xticks(range(n)); ax.set_xticklabels(labels, fontsize=10)
    ax.set_yticks(range(n)); ax.set_yticklabels(labels, fontsize=10)
    ax.set_title("Weekday Ring Subspace Overlap\ncos(θ₁)·cos(θ₂)  —  0=orthogonal, 1=identical",
                 fontsize=11)

    for i in range(n):
        for j in range(n):
            val = matrix[i, j]
            if not np.isnan(val):
                text_color = "white" if val < 0.3 else "black"
                ax.text(j, i, f"{val:.3f}", ha="center", va="center",
                        fontsize=10, color=text_color, fontweight="bold")

    plt.colorbar(im, ax=ax, label="Overlap score")
    fig.tight_layout()
    path = os.path.join(FIGURES_DIR, "fig4_overlap_heatmap.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 5 — Pullback: optimized vs linear r² (EN and FR)
# ══════════════════════════════════════════════════════════════════════════════
def fig5_pullback_comparison():
    langs = ["en", "fr"]
    x = np.arange(len(langs))
    w = 0.32

    fig, ax = plt.subplots(figsize=(6, 5))

    opt_vals = [PULLBACK[l][0] for l in langs]
    lin_vals = [PULLBACK[l][1] for l in langs]

    bars_opt = ax.bar(x - w/2, opt_vals, w, color=[LANG_COLORS[l] for l in langs],
                      alpha=0.9, label="Geodesic (optimized)", edgecolor="white")
    bars_lin = ax.bar(x + w/2, lin_vals, w, color=[LANG_COLORS[l] for l in langs],
                      alpha=0.45, label="Linear", edgecolor="white", hatch="///")

    for bar, val in zip(bars_opt, opt_vals):
        ax.text(bar.get_x() + bar.get_width()/2, val + 0.01, f"{val:.3f}",
                ha="center", va="bottom", fontsize=9, fontweight="bold")
    for bar, val in zip(bars_lin, lin_vals):
        ax.text(bar.get_x() + bar.get_width()/2, val + 0.01, f"{val:.3f}",
                ha="center", va="bottom", fontsize=9)

    # Annotation arrows showing which is better
    for i, lang in enumerate(langs):
        opt, lin = PULLBACK[lang]
        better = "geo" if opt > lin else "lin"
        color = LANG_COLORS[lang]
        sign = "+" if opt > lin else "−"
        delta = abs(opt - lin)
        ax.annotate(
            f"{sign}{delta:.2f}",
            xy=(i + w/2 if better == "lin" else i - w/2,
                max(opt, lin) + 0.03),
            ha="center", fontsize=9, color=color, fontstyle="italic"
        )

    ax.set_xticks(x)
    ax.set_xticklabels([LANG_LABELS[l] for l in langs], fontsize=11)
    ax.set_ylabel("Path recapitulation r² (k=32 neighbours)", fontsize=10)
    ax.set_ylim(0, 0.85)
    ax.set_title(
        "Pullback Quality: Geodesic vs Linear Paths\n"
        "(EN ring: geodesic > linear  |  FR no-ring: linear > geodesic)",
        fontsize=11
    )
    ax.legend(fontsize=9)
    ax.axhline(0.5, color="gray", lw=0.8, ls=":", alpha=0.5)

    fig.tight_layout()
    path = os.path.join(FIGURES_DIR, "fig5_pullback_comparison.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 6 — Safety vector cross-lingual projection
# ══════════════════════════════════════════════════════════════════════════════
def fig6_safety_projection():
    labels = ["English\n(source)", "Japanese", "Chinese", "French"]
    values = [1.000, 0.421, 0.242, 0.023]
    colors = [LANG_COLORS["en"], LANG_COLORS["ja"], LANG_COLORS["zh"], LANG_COLORS["fr"]]

    fig, ax = plt.subplots(figsize=(7, 4.5))
    bars = ax.barh(labels[::-1], [v * 100 for v in values[::-1]],
                   color=colors[::-1], edgecolor="white", alpha=0.88)

    for bar, val in zip(bars, values[::-1]):
        pct = val * 100
        ax.text(pct + 0.5, bar.get_y() + bar.get_height()/2,
                f"{pct:.1f}%", va="center", fontsize=10, fontweight="bold")

    ax.axvline(50, color="gray", lw=0.8, ls=":", alpha=0.6)
    ax.set_xlim(0, 108)
    ax.set_xlabel("Retained norm (%) when projecting English safety direction\nonto target language's 2-D ring subspace", fontsize=9)
    ax.set_title(
        "Cross-lingual Safety Transfer from English\n"
        "(subspace overlap = fraction of EN direction retained in target subspace)",
        fontsize=11
    )
    ax.tick_params(labelsize=10)

    fig.tight_layout()
    path = os.path.join(FIGURES_DIR, "fig6_safety_projection.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7 — Isometry vs coherence scatter
# ══════════════════════════════════════════════════════════════════════════════
def fig7_isometry_coherence():
    fig, ax = plt.subplots(figsize=(6, 5))

    for lang in LANGS:
        iso = ISOMETRY_R[lang]
        coh = COHERENCE[lang]
        color = LANG_COLORS[lang]
        is_ring = LANG_RING[lang]
        marker = "★" if is_ring else "●"

        ax.scatter(iso, coh, s=200, color=color, zorder=3,
                   marker="*" if is_ring else "o",
                   edgecolors="white", linewidths=0.8)
        ax.annotate(
            f"  {LANG_LABELS[lang]}\n  {'(ring)' if is_ring else ''}",
            (iso, coh), fontsize=9, color=color,
            xytext=(iso + 0.02, coh - 0.015),
        )

    ax.axvline(0, color="gray", lw=0.8, ls="--", alpha=0.5, label="r = 0")
    ax.axhline(0.8, color="gray", lw=0.8, ls=":", alpha=0.5, label="coherence = 0.8")

    ax.set_xlabel("Geometric path isometry (Pearson r)", fontsize=10)
    ax.set_ylabel("Geometric steering coherence", fontsize=10)
    ax.set_title(
        "Geometry vs. Functional Quality per Language\n"
        "★ = periodic ring  ● = open spline",
        fontsize=11
    )
    ax.set_xlim(-0.25, 1.1)
    ax.set_ylim(0.70, 1.02)
    ax.legend(fontsize=8)

    # Quadrant labels
    ax.text(0.55, 0.73, "Isometric + low coherence\n(EN: geometric precision)", fontsize=7.5,
            ha="center", color="gray", style="italic")
    ax.text(-0.15, 0.97, "Non-isometric + high coherence\n(ZH, JA: functional but not geometric)",
            fontsize=7.5, ha="center", color="gray", style="italic")

    fig.tight_layout()
    path = os.path.join(FIGURES_DIR, "fig7_isometry_coherence.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


def fig8_steering_coherence():
    """Grouped bar chart: cross-lingual vs same-language geometric steering coherence."""
    # Cross-lingual steering results (jobs 12573–12575, 2026-06-12)
    cross_lingual = {
        ("en", "zh"): {"mean": 0.9631, "se": 0.0005},  # EN ring → ZH prompts
        ("zh", "ja"): {"mean": 0.7701, "se": 0.0235},  # ZH spline → JA prompts
        ("en", "fr"): {"mean": 0.9802, "se": 0.0004},  # EN ring → FR prompts
    }
    # Same-language geometric coherence baselines (from path_steering criteria)
    same_lang = {
        "en": {"mean": 0.7829, "se": 0.0033},
        "zh": {"mean": 0.9664, "se": 0.0005},
        "ja": {"mean": 0.9785, "se": 0.0005},
        "fr": {"mean": 0.7445, "se": 0.0003},
    }
    # Subspace overlap for annotation
    overlap = {("en", "zh"): 0.242, ("zh", "ja"): 0.350, ("en", "fr"): 0.023}

    target_langs = ["zh", "ja", "fr"]
    target_labels = {"zh": "Chinese\n(ZH)", "ja": "Japanese\n(JA)", "fr": "French\n(FR)"}
    source_labels = {("en", "zh"): "EN→ZH", ("zh", "ja"): "ZH→JA", ("en", "fr"): "EN→FR"}

    fig, ax = plt.subplots(figsize=(7, 4.5))
    x = np.arange(len(target_langs))
    width = 0.35

    same_means = [same_lang[t]["mean"] for t in target_langs]
    same_ses   = [same_lang[t]["se"]   for t in target_langs]
    cross_keys = [("en", "zh"), ("zh", "ja"), ("en", "fr")]
    cross_means = [cross_lingual[k]["mean"] for k in cross_keys]
    cross_ses   = [cross_lingual[k]["se"]   for k in cross_keys]

    bars_same  = ax.bar(x - width/2, same_means,  width, yerr=same_ses,
                        capsize=4, color="#90CAF9", edgecolor="#1565C0",
                        linewidth=1.2, label="Same-language baseline")
    bars_cross = ax.bar(x + width/2, cross_means, width, yerr=cross_ses,
                        capsize=4, color="#FFCC80", edgecolor="#E65100",
                        linewidth=1.2, label="Cross-lingual steering")

    # Annotate source language + subspace overlap above each cross-lingual bar
    for i, (k, bar) in enumerate(zip(cross_keys, bars_cross)):
        ov = overlap[k]
        lbl = source_labels[k]
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + cross_ses[i] + 0.012,
                f"{lbl}\noverlap={ov:.3f}", ha="center", va="bottom",
                fontsize=7.5, color="#E65100", fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels([target_labels[t] for t in target_langs], fontsize=11)
    ax.set_ylabel("Geometric steering coherence", fontsize=11)
    ax.set_ylim(0, 1.15)
    ax.axhline(1.0, color="gray", lw=0.8, ls="--", alpha=0.5)
    ax.legend(fontsize=10, loc="upper left")
    ax.set_title("Cross-lingual steering coherence vs same-language baseline\n"
                 "(Llama 3.1 8B, weekday arithmetic, Layer 28 last-token)", fontsize=10)

    # Annotation box: key finding
    ax.text(0.98, 0.04,
            "EN ring (isometry=0.989) steers FR better\nthan FR's own spline (isometry=0.087)\n"
            "despite 2.3% subspace overlap.",
            transform=ax.transAxes, ha="right", va="bottom", fontsize=8,
            color="#555555", style="italic",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="#FFF9C4", edgecolor="#F9A825", alpha=0.85))

    fig.tight_layout()
    path = os.path.join(FIGURES_DIR, "fig8_steering_coherence.pdf")
    fig.savefig(path, bbox_inches="tight")
    fig.savefig(path.replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
    print(f"Saved {path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    print(f"Saving figures to: {FIGURES_DIR}")
    fig1_language_manifolds()
    fig2_joint_embedding()
    fig3_subspace_alignment()
    fig4_overlap_heatmap()
    fig5_pullback_comparison()
    fig6_safety_projection()
    fig7_isometry_coherence()
    fig8_steering_coherence()
    print("All figures saved.")
